# Generated by Django 3.2 on 2023-04-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_alter_patientvisit_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('patient_visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='patient.patientvisit')),
            ],
        ),
    ]
