# Generated by Django 3.2 on 2023-04-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='patient_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='visit.patientvisit'),
        ),
    ]
