# Generated by Django 3.2 on 2023-04-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_delete_patientvisit'),
        ('doctor', '0007_remove_doctor_fullname'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientvisits', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_visit', to='doctor.visit'),
        ),
    ]
