# Generated by Django 3.2 on 2023-04-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_alter_patientvisit_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisit',
            name='is_visited',
        ),
    ]
