# Generated by Django 3.2 on 2023-04-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
