# Generated by Django 3.2 on 2023-04-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'patient'), (3, 'doctor')], default=1)),
                ('receiver_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'patient'), (3, 'doctor')], default=1)),
                ('sender', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=10)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'read')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
