# Generated by Django 3.2 on 2023-04-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('support', '0002_auto_20230411_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormessage',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'seen_only'), (3, 'answered')], default=1),
        ),
        migrations.CreateModel(
            name='PatientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'seen_only'), (3, 'answered')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='patient.patient')),
            ],
        ),
    ]
