# Generated by Django 3.2 on 2023-04-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientvisit_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisit',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='visit',
        ),
    ]
