# Generated by Django 3.2 on 2023-04-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_alter_refund_patient_visit'),
        ('patient', '0003_auto_20230412_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientVisit',
        ),
    ]
