# Generated by Django 3.2 on 2023-04-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('person_code', models.CharField(max_length=10)),
                ('medical_code', models.CharField(max_length=5)),
                ('office_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='location.city')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('amount', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=11)),
                ('person_code', models.CharField(max_length=10)),
                ('medical_code', models.CharField(max_length=12)),
                ('office_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True, null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'accept'), (3, 'reject')], default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='requests/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='location.city')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='doctor.expertise')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctor.expertise'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
