# Generated by Django 3.2 on 2023-04-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'accept')], default=1),
        ),
    ]
